quoteServiceURL: http://quote-service-qa.cfapps.io/quote

security:
  basic:
    enabled: false # turn off securing our application endpoints sdfsd

management:
  security:
    enabled: false # turn off securing the actuator endpoints